_base_ = "./yolov8_s_syncbn_fast_8xb16-500e_coco.py"

data_root = "data/vg/"
class_name = (
    "man",
    "window",
    "person",
    "tree",
    "building",
    "shirt",
    "wall",
    "woman",
    "sign",
    "sky",
    "ground",
    "light",
    "grass",
    "cloud",
    "pole",
    "car",
    "table",
    "leaf",
    "leg",
    "hand",
    "head",
    "water",
    "hair",
    "people",
    "ear",
    "eye",
    "shoe",
    "plate",
    "flower",
    "wheel",
    "line",
    "door",
    "chair",
    "letter",
    "pant",
    "fence",
    "train",
    "floor",
    "road",
    "shadow",
    "hat",
    "street",
    "snow",
    "jacket",
    "boy",
    "rock",
    "boat",
    "handle",
    "nose",
    "horse",
    "clock",
    "giraffe",
    "bird",
    "elephant",
    "tail",
    "sidewalk",
    "stripe",
    "girl",
    "zebra",
    "plane",
    "arm",
    "bus",
    "umbrella",
    "helmet",
    "field",
    "cow",
    "short",
    "dog",
    "foot",
    "track",
    "tile",
    "bag",
    "number",
    "face",
    "bench",
    "bottle",
    "glass",
    "sheep",
    "kite",
    "wave",
    "cat",
    "banana",
    "food",
    "tire",
    "bush",
    "post",
    "spot",
    "plant",
    "picture",
    "player",
    "pillow",
    "motorcycle",
    "bear",
    "surfboard",
    "truck",
    "logo",
    "bike",
    "roof",
    "bowl",
    "skateboard",
    "glasses",
    "branch",
    "shelf",
    "brick",
    "box",
    "mirror",
    "house",
    "background",
    "pizza",
    "button",
    "cap",
    "glove",
    "book",
    "trunk",
    "mountain",
    "jean",
    "cup",
    "mouth",
    "dirt",
    "top",
    "part",
    "board",
    "flag",
    "wing",
    "paper",
    "ball",
    "counter",
    "lamp",
    "bed",
    "vehicle",
    "seat",
    "sink",
    "headlight",
    "child",
    "animal",
    "beach",
    "cabinet",
    "sand",
    "ski",
    "neck",
    "writing",
    "vase",
    "hill",
    "reflection",
    "coat",
    "airplane",
    "sock",
    "laptop",
    "toilet",
    "phone",
    "edge",
    "cake",
    "wire",
    "sunglass",
    "towel",
    "desk",
    "word",
    "tower",
    "finger",
    "tie",
    "frisbee",
    "orange",
    "container",
    "skier",
    "lady",
    "ceiling",
    "curtain",
    "frame",
    "ocean",
    "apple",
    "racket",
    "fruit",
    "donut",
    "keyboard",
    "pot",
    "knob",
    "design",
    "windshield",
    "horn",
    "back",
    "paw",
    "wood",
    "guy",
    "engine",
    "stone",
    "basket",
    "fork",
    "bat",
    "carrot",
    "knife",
    "boot",
    "railing",
    "stand",
    "sneaker",
    "surfer",
    "bicycle",
    "vegetable",
    "broccoli",
    "sticker",
    "suitcase",
    "couch",
    "kid",
    "backpack",
    "key",
    "collar",
    "drawer",
    "screen",
    "blanket",
    "photo",
    "stem",
    "cheese",
    "napkin",
    "sandwich",
    "hole",
    "tag",
    "bread",
    "van",
    "lid",
    "dress",
    "watch",
    "tray",
    "men",
    "tomato",
    "bar",
    "uniform",
    "sweater",
    "traffic light",
    "cone",
    "room",
    "court",
    "strap",
    "rail",
    "bridge",
    "cord",
    "lettering",
    "candle",
    "faucet",
    "mane",
    "arrow",
    "object",
    "pavement",
    "computer",
    "hoof",
    "ripple",
    "camera",
    "suit",
    "air",
    "spoon",
    "white",
    "fur",
    "dish",
    "side",
    "platform",
    "wrist",
    "sleeve",
    "meat",
    "pipe",
    "curb",
    "stick",
    "snowboard",
    "patch",
    "vest",
    "bathroom",
    "statue",
    "rope",
    "step",
    "can",
    "hydrant",
    "luggage",
    "stove",
    "corner",
    "license plate",
    "base",
    "mouse",
    "sauce",
    "carpet",
    "monitor",
    "front",
    "ring",
    "circle",
    "rack",
    "t-shirt",
    "beak",
    "street sign",
    "teddy bear",
    "banner",
    "knee",
    "a",
    "rug",
    "cloth",
    "chain",
    "tv",
    "belt",
    "shade",
    "pillar",
    "street light",
    "goggles",
    "string",
    "onion",
    "catcher",
    "stair",
    "spectator",
    "black",
    "feather",
    "tusk",
    "this",
    "blue sky",
    "distance",
    "paint",
    "white clouds",
    "jersey",
    "area",
    "tennis racket",
    "remote",
    "oven",
    "the",
    "item",
    "weed",
    "trim",
    "ramp",
    "balcony",
    "purse",
    "cell phone",
    "hot dog",
    "label",
    "skirt",
    "jet",
    "ski pole",
    "gravel",
    "kitchen",
    "whisker",
    "wetsuit",
    "park",
    "surface",
    "skateboarder",
    "body",
    "bracelet",
    "cover",
    "doughnut",
    "dot",
    "column",
    "tennis court",
    "pen",
    "bun",
    "name",
    "gate",
    "television",
    "tree trunk",
    "awning",
    "log",
    "pepper",
    "blind",
    "bolt",
    "graffiti",
    "band",
    "scarf",
    "shore",
    "tip",
    "baby",
    "batter",
    "pan",
    "cart",
    "walkway",
    "bottom",
    "river",
    "panel",
    "umpire",
    "jar",
    "pocket",
    "net",
    "sheet",
    "cellphone",
    "necklace",
    "crack",
    "baseball",
    "shrub",
    "runway",
    "refrigerator",
    "sofa",
    "topping",
    "green",
    "train car",
    "wine",
    "speaker",
    "path",
    "slice",
    "sun",
    "trash can",
    "microwave",
    "shoulder",
    "crust",
    "metal",
    "painting",
    "outlet",
    "mark",
    "clothes",
    "piece",
    "concrete",
    "holder",
    "star",
    "red",
    "square",
    "pond",
    "tent",
    "fire hydrant",
    "cushion",
    "sandal",
    "duck",
    "bucket",
    "utensil",
    "mug",
    "beard",
    "doorway",
    "poster",
    "toy",
    "structure",
    "pattern",
    "controller",
    "toothbrush",
    "snowboarder",
    "blue",
    "scene",
    "advertisement",
    "chimney",
    "vent",
    "city",
    "stop sign",
    "group",
    "lettuce",
    "propeller",
    "forest",
    "tennis ball",
    "tablecloth",
    "fan",
    "teeth",
    "slope",
    "baseball player",
    "text",
    "pepperoni",
    "pitcher",
    "train tracks",
    "fridge",
    "store",
    "row",
    "scissors",
    "potato",
    "hood",
    "cable",
    "case",
    "symbol",
    "earring",
    "outfit",
    "decoration",
    "parking lot",
    "tank",
    "wristband",
    "suv",
    "frosting",
    "pane",
    "roman numeral",
    "wiper",
    "palm tree",
    "rider",
    "tennis player",
    "ribbon",
    "petal",
    "egg",
    "straw",
    "rim",
    "block",
    "numeral",
    "hotdog",
    "liquid",
    "thumb",
    "toilet paper",
    "crowd",
    "nail",
    "white shirt",
    "elbow",
    "display",
    "marking",
    "mushroom",
    "signal",
    "smoke",
    "clothing",
    "strawberry",
    "cockpit",
    "goat",
    "slat",
    "dock",
    "eyebrow",
    "hay",
    "bumper",
    "couple",
    "smiling woman",
    "drink",
    "stool",
    "headboard",
    "rose",
    "ladder",
    "screw",
    "chicken",
    "olive",
    "chest",
    "tongue",
    "land",
    "brush",
    "lake",
    "pastry",
    "tub",
    "footprint",
    "eyeglass",
    "lip",
    "green leaves",
    "section",
    "cleat",
    "meter",
    "hoodie",
    "mat",
    "blue jeans",
    "game",
    "pad",
    "hillside",
    "bin",
    "white line",
    "grill",
    "claw",
    "wine glass",
    "cupcake",
    "countertop",
    "motorbike",
    "foam",
    "fabric",
    "blade",
    "pile",
    "scooter",
    "beam",
    "print",
    "salad",
    "grape",
    "green grass",
    "headband",
    "tank top",
    "burner",
    "blue shirt",
    "mask",
    "sprinkle",
    "planter",
    "brown",
    "vegetation",
    "airport",
    "tarmac",
    "mitt",
    "ship",
    "station",
    "spoke",
    "passenger",
    "shutter",
    "canopy",
    "sail",
    "border",
    "barrier",
    "sweatshirt",
    "skin",
    "skater",
    "sunlight",
    "trash",
    "cement",
    "lemon",
    "wrinkle",
    "arch",
    "fireplace",
    "nostril",
    "crate",
    "hinge",
    "cross",
    "drain",
    "crosswalk",
    "urinal",
    "fry",
    "leash",
    "he",
    "roll",
    "lace",
    "ledge",
    "zipper",
    "rod",
    "yellow",
    "wet suit",
    "handlebar",
    "image",
    "tail light",
    "lawn",
    "magnet",
    "balloon",
    "right hand",
    "lot",
    "ponytail",
    "stain",
    "crumb",
    "bathtub",
    "bow",
    "visor",
    "home plate",
    "landing gear",
    "lamp post",
    "beer",
    "boulder",
    "counter top",
    "left hand",
    "magazine",
    "enclosure",
    "icing",
    "left",
    "tennis shoe",
    "strip",
    "shower",
    "toilet seat",
    "right",
    "streetlight",
    "tennis",
    "tattoo",
    "traffic signal",
    "chin",
    "snout",
    "rice",
    "soap",
    "fencing",
    "tarp",
    "apron",
    "foliage",
    "lamb",
    "dresser",
    "light pole",
    "switch",
    "emblem",
    "heart",
    "sausage",
    "twig",
    "bean",
    "saucer",
    "tape",
    "parking meter",
    "machine",
    "sea",
    "comforter",
    "hook",
    "carriage",
    "dessert",
    "trailer",
    "male",
    "fish",
    "bunch",
    "dispenser",
    "power lines",
    "bell",
    "mound",
    "cupboard",
    "stack",
    "street lamp",
    "plastic",
    "trail",
    "pasture",
    "horizon",
    "sailboat",
    "coffee table",
    "ketchup",
    "clock tower",
    "yard",
    "antenna",
    "stuffed animal",
    "plank",
    "smile",
    "pedestrian",
    "coffee",
    "tissue",
    "light fixture",
    "water bottle",
    "front wheel",
    "saddle",
    "bookshelf",
    "table cloth",
    "outside",
    "baseball bat",
    "billboard",
    "fixture",
    "fingernail",
    "telephone",
    "steeple",
    "hose",
    "church",
    "driver",
    "white plate",
    "restaurant",
    "white letter",
    "barrel",
    "hedge",
    "ski poles",
    "cutting board",
    "black shirt",
    "fin",
    "human",
    "belly",
    "gear",
    "surf board",
    "racquet",
    "end",
    "pine tree",
    "doll",
    "pier",
    "home",
    "baseball field",
    "moss",
    "baseball cap",
    "pigeon",
    "puddle",
    "red shirt",
    "cucumber",
    "color",
    "deck",
    "ice",
    "stroller",
    "nightstand",
    "marker",
    "grate",
    "asphalt",
    "pickle",
    "crane",
    "card",
    "glass window",
    "seagull",
    "chip",
    "drawing",
    "mast",
    "mustache",
    "entrance",
    "cab",
    "soup",
    "harness",
    "left ear",
    "bull",
    "archway",
    "plug",
    "cage",
    "bacon",
    "seed",
    "pebble",
    "bark",
    "zoo",
    "noodle",
    "silverware",
    "remote control",
    "clock face",
    "black pants",
    "trashcan",
    "menu",
    "support",
    "newspaper",
    "trouser",
    "brown hair",
    "front leg",
    "aircraft",
    "lock",
    "toe",
    "cooler",
    "garbage can",
    "stomach",
    "wrist band",
    "right ear",
    "mustard",
    "white cloud",
    "mud",
    "figure",
    "nut",
    "reflector",
    "two",
    "meal",
    "opening",
    "paddle",
    "shaker",
    "female",
    "train track",
    "headphone",
    "flooring",
    "dugout",
    "art",
    "buoy",
    "bedroom",
    "knot",
    "veggie",
    "tshirt",
    "soccer ball",
    "left eye",
    "taxi",
    "toilet bowl",
    "microphone",
    "pair",
    "traffic sign",
    "tee shirt",
    "train station",
    "traffic",
    "intersection",
    "forehead",
    "spinach",
    "light post",
    "platter",
    "bleacher",
    "day",
    "device",
    "living room",
    "brick wall",
    "power line",
    "computer monitor",
    "blouse",
    "light switch",
    "bubble",
    "french fry",
    "red light",
    "roman numerals",
    "shop",
    "she",
    "porch",
    "tool",
    "staircase",
    "tube",
    "sculpture",
    "bulb",
    "stop",
    "splash",
    "blender",
    "chocolate",
    "wool",
    "pool",
    "wagon",
    "control",
    "t shirt",
    "toddler",
    "tree branch",
    "right eye",
    "limb",
    "metal pole",
    "outdoors",
    "spire",
    "juice",
    "lap",
    "fence post",
    "polar bear",
    "mattress",
    "windshield wiper",
    "package",
    "figurine",
    "dome",
    "debris",
    "placemat",
    "ad",
    "adult",
    "front tire",
    "table top",
    "dishwasher",
    "berry",
    "black hair",
    "island",
    "pedal",
    "bristle",
    "candy",
    "tooth",
    "bedspread",
    "diamond",
    "furniture",
    "kettle",
    "dial",
    "skyscraper",
    "bracket",
    "triangle",
    "tennis shoes",
    "kitten",
    "fender",
    "wine bottle",
    "traffic lights",
    "roadway",
    "lamp shade",
    "cookie",
    "stop light",
    "equipment",
    "white lines",
    "brown spot",
    "drape",
    "character",
    "officer",
    "foreground",
    "bead",
    "photograph",
    "center",
    "ski lift",
    "barn",
    "buckle",
    "wii",
    "shoreline",
    "hanger",
    "pie",
    "cattle",
    "moped",
    "ornament",
    "soda",
    "cabinet door",
    "pineapple",
    "vine",
    "kickstand",
    "worker",
    "silver",
    "it",
    "wrapper",
    "garage",
    "note",
    "handbag",
    "cliff",
    "corn",
    "cream",
    "globe",
    "highway",
    "calf",
    "sugar",
    "pink",
    "lampshade",
    "sedan",
    "artwork",
    "driveway",
    "icon",
    "ham",
    "left arm",
    "plaque",
    "blonde hair",
    "cheek",
    "muffin",
    "bookcase",
    "time",
    "middle",
    "coffee cup",
    "garden",
    "cabin",
    "jug",
    "pasta",
    "stairway",
    "spatula",
    "bank",
    "lighting",
    "pear",
    "carton",
    "waist",
    "beverage",
    "bridle",
    "cd",
    "stoplight",
    "view",
    "front legs",
    "bandana",
    "tunnel",
    "foil",
    "bad sentence",
    "side mirror",
    "pea",
    "someone",
    "right arm",
    "beanie",
    "goose",
    "armrest",
    "chandelier",
    "decal",
    "rust",
    "spice",
    "milk",
    "pizza slice",
    "bus stop",
    "biker",
    "pencil",
    "green shirt",
    "notebook",
    "green leaf",
    "graphic",
    "patio",
    "canoe",
    "telephone pole",
    "palm trees",
    "window pane",
    "gray",
    "toaster",
    "blueberry",
    "door handle",
    "pathway",
    "stump",
    "stalk",
    "shingle",
    "picture frame",
    "right leg",
    "bikini",
    "appliance",
    "material",
    "socket",
    "jeep",
    "motor",
    "oar",
    "necktie",
    "left leg",
    "taillight",
    "american flag",
    "divider",
    "costume",
    "watermelon",
    "herd",
    "garbage",
    "two people",
    "window sill",
    "wallpaper",
    "vas",
    "plastic bag",
    "landscape",
    "baseball glove",
    "train engine",
    "lighthouse",
    "thigh",
    "covering",
    "green tree",
    "shed",
    "wii remote",
    "pumpkin",
    "ridge",
    "flamingo",
    "guitar",
    "yellow line",
    "large",
    "man's head",
    "palm",
    "latch",
    "heel",
    "butter",
    "soil",
    "white sign",
    "speck",
    "shape",
    "mouse pad",
    "clip",
    "inside",
    "toothpick",
    "greenery",
    "stadium",
    "mantle",
    "black jacket",
    "guard",
    "fountain",
    "steam",
    "pilot",
    "rain",
    "shower head",
    "ram",
    "dark hair",
    "flame",
    "brick building",
    "ottoman",
    "cuff",
    "slab",
    "shower curtain",
    "condiment",
    "shoelace",
    "parasail",
    "knee pad",
    "puppy",
    "railroad",
    "brake light",
    "steering wheel",
    "french fries",
    "muzzle",
    "pack",
    "space",
    "freezer",
    "down",
    "cigarette",
    "butterfly",
    "pony tail",
    "herb",
    "skiis",
    "wooden",
    "glare",
    "sole",
    "cherry",
    "lime",
    "is",
    "handrail",
    "policeman",
    "shrimp",
    "lift",
    "family",
    "ski slope",
    "bouquet",
    "wooden table",
    "lens",
    "black letter",
    "booth",
    "mannequin",
    "flip flops",
    "baby elephant",
    "left foot",
    "cardboard",
    "man's hand",
    "cabbage",
    "skate park",
    "grey",
    "cauliflower",
    "yellow shirt",
    "coffee mug",
    "shrubbery",
    "parrot",
    "spray",
    "stuff",
    "trolley",
    "flip flop",
    "picnic table",
    "canister",
    "watermark",
    "white wall",
    "pony",
    "bow tie",
    "little girl",
    "manhole",
    "baseboard",
    "chopstick",
    "peak",
    "door knob",
    "radiator",
    "head light",
    "thing",
    "rear",
    "netting",
    "black shorts",
    "green trees",
    "air conditioner",
    "set",
    "teapot",
    "toilet lid",
    "coaster",
    "lanyard",
    "man's",
    "point",
    "mountain range",
    "feeder",
    "tree branches",
    "skiier",
    "peel",
    "rein",
    "brocolli",
    "something",
    "mailbox",
    "hubcap",
    "dvd",
    "sunset",
    "toast",
    "overpass",
    "skate board",
    "wristwatch",
    "pancake",
    "range",
    "eyelash",
    "towel rack",
    "needle",
    "peach",
    "basin",
    "mother",
    "back wheel",
    "facial hair",
    "yellow flower",
    "right foot",
    "locomotive",
    "street lights",
    "burger",
    "lane",
    "market",
    "sweatband",
    "trick",
    "seaweed",
    "night stand",
    "salt shaker",
    "deer",
    "stall",
    "wii controller",
    "packet",
    "tap",
    "disc",
    "wake",
    "computer mouse",
    "back leg",
    "tine",
    "siding",
    "cardboard box",
    "cloudy sky",
    "bud",
    "bagel",
    "stove top",
    "sill",
    "hip",
    "pin",
    "s",
    "map",
    "business",
    "coffee maker",
    "desert",
    "soccer player",
    "stone wall",
    "median",
    "leave",
    "rivet",
    "storefront",
    "robe",
    "lantern",
    "audience",
    "ice cream",
    "doorknob",
    "portion",
    "police officer",
    "ankle",
    "bang",
    "badge",
    "pedestal",
    "flower pot",
    "red sign",
    "swan",
    "mousepad",
    "white car",
    "grip",
    "white letters",
    "back tire",
    "paper towels",
    "p",
    "up",
    "computer screen",
    "end table",
    "brace",
    "game controller",
    "shelter",
    "plain",
    "avocado",
    "an",
    "motorcyclist",
    "arm rest",
    "seasoning",
    "short hair",
    "stream",
    "striped shirt",
    "back legs",
    "tennis net",
    "cycle",
    "printer",
    "raft",
    "trash bin",
    "lamppost",
    "barricade",
    "hotel",
    "grassy area",
    "soap dispenser",
    "long hair",
    "minivan",
    "handle bars",
    "front window",
    "produce",
    "pink shirt",
    "light reflection",
    "blue sign",
    "street signs",
    "hour hand",
    "jockey",
    "these",
    "small",
    "vanity",
    "dough",
    "date",
    "white snow",
    "grout",
    "office",
    "fire",
    "cracker",
    "wrap",
    "young man",
    "photographer",
    "basil",
    "black hat",
    "quilt",
    "utility pole",
    "toothpaste",
    "bill",
    "green light",
    "traffic cone",
    "rectangle",
    "briefcase",
    "metal fence",
    "skull",
    "ski pants",
    "hot dogs",
    "white pants",
    "tongs",
    "slipper",
    "knee pads",
    "seam",
    "monkey",
    "road sign",
    "panda",
    "video games",
    "black car",
    "red jacket",
    "squash",
    "minute hand",
    "handle bar",
    "celery",
    "brown horse",
    "compartment",
    "baseball game",
    "fire truck",
    "harbor",
    "white stripe",
    "black nose",
    "stage",
    "pine trees",
    "cooky",
    "scale",
    "roadside",
    "crown",
    "flap",
    "folder",
    "skyline",
    "ipod",
    "calendar",
    "root",
    "molding",
    "tennis racquet",
    "windowsill",
    "bib",
    "paper plate",
    "piano",
    "tabletop",
    "mulch",
    "sign post",
    "castle",
    "dark",
    "exhaust",
    "prong",
    "gas tank",
    "town",
    "ocean waves",
    "white tile",
    "blazer",
    "t",
    "ski boot",
    "brand",
    "butt",
    "goatee",
    "back pack",
    "slot",
    "valley",
    "brown spots",
    "paper towel",
    "sunflower",
    "stabilizer",
    "hen",
    "bride",
    "raspberry",
    "streamer",
    "student",
    "hut",
    "fox",
    "terrain",
    "there",
    "toilet tank",
    "window frame",
    "scoreboard",
    "wallet",
    "tractor",
    "soldier",
    "blue jacket",
    "tulip",
    "railway",
    "half",
    "hallway",
    "daytime",
    "torso",
    "lion",
    "side window",
    "side walk",
    "cop",
    "old woman",
    "fringe",
    "x",
    "tablet",
    "price",
    "black stripe",
    "groove",
    "snack",
    "grass field",
    "antelope",
    "man's face",
    "three",
    "valve",
    "railroad tracks",
    "police",
    "cereal",
    "wooden fence",
    "building window",
    "moon",
    "turf",
    "streak",
    "candle holder",
    "laptop computer",
    "chef",
    "red car",
    "fog",
    "snowflake",
    "stirrup",
    "dandelion",
    "skiing",
    "tangerine",
    "desktop",
    "garage door",
    "ocean water",
    "swimsuit",
    "binder",
    "parachute",
    "snowsuit",
    "ceiling light",
    "white building",
    "guard rail",
    "toiletry",
    "advertising",
    "hind leg",
    "terminal",
    "beef",
    "salt",
    "park bench",
    "shell",
    "red stripe",
    "gutter",
    "thread",
    "side table",
    "tin",
    "eye glasses",
    "cloudy",
    "floret",
    "scratch",
    "oven door",
    "blue pants",
    "they",
    "snow board",
    "gun",
    "radio",
    "orange juice",
    "black bag",
    "dash",
    "curve",
    "undershirt",
    "team",
    "parasol",
    "cactus",
    "purple",
    "black shoe",
    "closet",
    "door frame",
    "meadow",
    "o",
    "crest",
    "windshield wipers",
    "teddy",
    "disk",
    "2",
    "fern",
    "kayak",
    "train cars",
    "polka dot",
    "manhole cover",
    "page",
    "orange shirt",
    "carving",
    "white hat",
    "exhaust pipe",
    "glaze",
    "e",
    "video game",
    "wrist watch",
    "rear wheel",
    "charger",
    "pine",
    "cane",
    "rag",
    "spike",
    "steak",
    "paneling",
    "metal bar",
    "accent",
    "layer",
    "leather",
    "sponge",
    "friend",
    "rooftop",
    "w",
    "braid",
    "spectacle",
    "heater",
    "mixer",
    "overall",
    "clay",
    "yellow sign",
    "boarder",
    "drop",
    "groom",
    "electrical outlet",
    "interior",
    "chalk",
    "ivy",
    "dust",
    "black shoes",
    "crease",
    "turkey",
    "parsley",
    "hand rail",
    "evergreen",
    "silhouette",
    "white shorts",
    "stocking",
    "name tag",
    "tv stand",
    "litter",
    "one",
    "tourist",
    "tall grass",
    "wooden post",
    "pail",
    "tassel",
    "black tire",
    "floor tile",
    "sack",
    "monument",
    "light bulb",
    "stuffed bear",
    "snow pants",
    "coach",
    "tea",
    "walking",
    "legging",
    "pump",
    "link",
    "mesh",
    "soccer",
    "ostrich",
    "subway",
    "grain",
    "dumpster",
    "dryer",
    "blue shorts",
    "wooden bench",
    "ox",
    "ski boots",
    "vein",
    "breast",
    "easel",
    "armchair",
    "pink flower",
    "muffler",
    "safety cone",
    "pajama",
    "entertainment center",
    "white bowl",
    "restroom",
    "on",
    "bump",
    "face mask",
    "woman's",
    "christmas tree",
    "owl",
    "tail feathers",
    "portrait",
    "signboard",
    "buggy",
    "radish",
    "signal light",
    "tall building",
    "shield",
    "skatepark",
    "green pepper",
    "overhang",
    "apartment",
    "white lettering",
    "coin",
    "brown grass",
    "farm",
    "gazelle",
    "oil",
    "clump",
    "sandwhich",
    "soap dish",
    "gap",
    "moustache",
    "pew",
    "right wing",
    "backsplash",
    "vessel",
    "white shoe",
    "clasp",
    "shin guard",
    "train platform",
    "hamburger",
    "unit",
    "life preserver",
    "bathing suit",
    "drum",
    "grafitti",
    "droplet",
    "match",
    "shopping bag",
    "weather vane",
    "left wing",
    "mitten",
    "coffee pot",
    "tissue box",
    "skylight",
    "pottery",
    "garnish",
    "beer bottle",
    "ski jacket",
    "teddy bears",
    "melon",
    "open",
    "playground",
    "website",
    "skillet",
    "outfield",
    "silver car",
    "pickup truck",
    "sunshine",
    "tomato slice",
    "jet engine",
    "conductor",
    "elbow pad",
    "tea kettle",
    "green bush",
    "syrup",
    "product",
    "number 2",
    "rock wall",
    "bowtie",
    "smoke stack",
    "slide",
    "cowboy hat",
    "boardwalk",
    "life jacket",
    "keypad",
    "floor lamp",
    "dip",
    "tail lights",
    "mural",
    "dinner",
    "donkey",
    "evergreen tree",
    "pylon",
    "toenail",
    "3",
    "tall tree",
    "bike rack",
    "buffalo",
    "suspender",
    "knuckle",
    "spout",
    "skate",
    "neck tie",
    "gold",
    "clear",
    "pepper shaker",
    "runner",
    "tail fin",
    "gravy",
    "banana bunch",
    "ceiling fan",
    "soda can",
    "referee",
    "elephant trunk",
    "tomato sauce",
    "orange slice",
    "tile floor",
    "goal",
    "lunch",
    "bath tub",
    "pizza crust",
    "surf",
    "throw pillow",
    "lipstick",
    "green sign",
    "pallet",
    "beach chair",
    "flag pole",
    "tree leaves",
    "tomatoe",
    "trough",
    "head band",
    "hill side",
    "automobile",
    "cargo",
    "swim trunks",
    "blue water",
    "tuft",
    "brake",
    "movie",
    "asparagus",
    "stapler",
    "foilage",
    "google",
    "surfing",
    "kneepad",
    "baseball uniform",
    "book shelf",
    "breakfast",
    "detail",
    "loop",
    "garlic",
    "canal",
    "envelope",
    "stovetop",
    "lining",
    "school bus",
    "rainbow",
    "flyer",
    "information",
    "bed spread",
    "place",
    "black spot",
    "scissor",
    "spine",
    "white writing",
    "white paper",
    "ski tracks",
    "stitching",
    "5",
    "two men",
    "lapel",
    "suit jacket",
    "wooden chair",
    "tan",
    "tortilla",
    "partition",
    "grass patch",
    "woman's hand",
    "podium",
    "place mat",
    "tail wing",
    "brim",
    "udder",
    "chunk",
    "entryway",
    "seating",
    "urn",
    "rearview mirror",
    "mountainside",
    "antler",
    "little boy",
    "white spot",
    "mango",
    "red pepper",
    "underside",
    "nike logo",
    "night",
    "long",
    "bedding",
    "standing",
    "white flower",
    "athlete",
    "powder",
    "clock hand",
    "racer",
    "plunger",
    "glass door",
    "cyclist",
    "croissant",
    "electronics",
    "outline",
    "tights",
    "daisy",
    "baseball hat",
    "ski suit",
    "toilet brush",
    "12",
    "chalkboard",
    "ashtray",
    "broom",
    "kiwi",
    "wreath",
    "red hair",
    "tripod",
    "white flowers",
    "pillowcase",
    "yacht",
    "streetlamp",
    "battery",
    "reign",
    "fire extinguisher",
    "jelly",
    "birthday cake",
    "steer",
    "powerlines",
    "flagpole",
    "signpost",
    "license",
    "young boy",
    "polka dots",
    "n",
    "relish",
    "dude",
    "office chair",
    "framed picture",
    "cobblestone",
    "yellow lines",
    "liner",
    "bathroom sink",
    "zucchini",
    "purple flower",
    "red letter",
    "young girl",
    "swirl",
    "bell pepper",
    "black coat",
    "black letters",
    "white pillow",
    "scaffolding",
    "comb",
    "dressing",
    "person's head",
    "sun glasses",
    "life vest",
    "cape",
    "6",
    "walk",
    "level",
    "woman's head",
    "red flower",
    "stud",
    "turbine",
    "guardrail",
    "carrier",
    "store front",
    "r",
    "hump",
    "bed frame",
    "wood table",
    "biscuit",
    "passenger train",
    "fuselage",
    "padding",
    "computer keyboard",
    "carpeting",
    "lever",
    "city street",
    "firetruck",
    "white surfboard",
    "jaw",
    "pupil",
    "right side",
    "tea pot",
    "jam",
    "potted plant",
    "clear sky",
    "tanktop",
    "copyright",
    "tennis match",
    "cub",
    "nozzle",
    "wild",
    "brownie",
    "alarm clock",
    "tree line",
    "white truck",
    "iron",
    "dress shirt",
    "white cap",
    "small window",
    "talon",
    "brown cow",
    "rear tire",
    "pendant",
    "food truck",
    "sail boat",
    "black eye",
    "shower door",
    "ski goggles",
    "stuffed animals",
    "white toilet",
    "plantain",
    "black cow",
    "black pole",
    "blue car",
    "courtyard",
    "canvas",
    "table lamp",
    "backside",
    "four",
    "passenger car",
    "eagle",
    "propellor",
    "slack",
    "exit sign",
    "steel",
    "passenger window",
    "facade",
    "orange cone",
    "supply",
    "green plant",
    "butter knife",
    "bloom",
    "port",
    "helicopter",
    "gray shirt",
    "freckle",
    "wire fence",
    "motor bike",
    "wine glasses",
    "power cord",
    "yarn",
    "white stripes",
    "forearm",
    "cylinder",
    "flour",
    "blue stripe",
    "pillow case",
    "white shoes",
    "black suit",
    "trash bag",
    "marina",
    "signage",
    "float",
    "stopper",
    "plaid shirt",
    "mountain top",
    "curly hair",
    "smiling",
    "white sheep",
    "angel",
    "indicator",
    "cardigan",
    "gown",
    "cork",
    "together",
    "teenager",
    "yellow flowers",
    "underbelly",
    "m",
    "tree stump",
    "spool",
    "ball cap",
    "gazebo",
    "footboard",
    "frond",
    "chair back",
    "wheelchair",
    "plastic container",
    "4",
    "microwave oven",
    "kitty",
    "1",
    "red hat",
    "blossom",
    "dvd player",
    "white boat",
    "black number",
    "pouch",
    "plumbing",
    "pizza box",
    "marble",
    "cluster",
    "pamphlet",
    "hand towel",
    "cowboy",
    "white door",
    "white sock",
    "control panel",
    "skateboarding",
    "paper bag",
    "white board",
    "black writing",
    "camper",
    "letter s",
    "tree top",
    "wooden pole",
    "timer",
    "snow suit",
    "dashboard",
    "tv screen",
    "weather",
    "pickup",
    "white house",
    "silver handle",
    "handkerchief",
    "metal post",
    "formation",
    "brand name",
    "smartphone",
    "letter o",
    "gauge",
    "flower petal",
    "white van",
    "lotion",
    "notepad",
    "barbed wire",
    "yolk",
    "black bird",
    "customer",
    "railroad track",
    "baseball players",
    "ingredient",
    "wildflower",
    "purple shirt",
    "gas station",
    "receipt",
    "clock hands",
    "pink flowers",
    "safety vest",
    "armband",
    "sword",
    "dirt bike",
    "brown bear",
    "fire escape",
    "wooded area",
    "bicyclist",
    "plastic cup",
    "display case",
    "dragon",
    "mantel",
    "red umbrella",
    "dirt road",
    "console",
    "red wine",
    "dirt patch",
    "gentleman",
    "air vent",
    "cartoon",
    "number 3",
    "destination",
    "cut",
    "penguin",
    "green beans",
    "white horse",
    "pitch",
    "folding chair",
    "round",
    "shoulder bag",
    "khaki",
    "red sauce",
    "blond hair",
    "football",
    "binding",
    "bruise",
    "black bear",
    "smokestack",
    "luggage cart",
    "black wheel",
    "waterfall",
    "footstep",
    "jalapeno",
    "calculator",
    "red brick",
    "swing",
    "grease",
    "left side",
    "tiger",
    "wooden floor",
    "spotlight",
    "skateboard ramp",
    "bamboo",
    "infield",
    "banana slice",
    "hangar",
    "gray hair",
    "letter t",
    "hoop",
    "garment",
    "rib",
    "white towel",
    "writting",
    "lighter",
    "pant leg",
    "b",
    "nail polish",
    "bone",
    "dining table",
    "police car",
    "power pole",
    "good",
    "cook",
    "treat",
    "storage",
    "red bus",
    "mole",
    "grassy field",
    "wax paper",
    "swimmer",
    "person's hand",
    "train front",
    "jumpsuit",
    "eggplant",
    "taxi cab",
    "recliner",
    "direction",
    "parking",
    "white cup",
    "back window",
    "plastic bottle",
    "letter p",
    "number 1",
    "pearl",
    "sweat band",
    "sitting",
    "sled",
    "front end",
    "large rock",
    "kick stand",
    "wood floor",
    "whipped cream",
    "suit case",
    "hair dryer",
    "decor",
    "connector",
    "halter",
    "money",
    "ocean wave",
    "sideburn",
    "projector",
    "empty",
    "metal railing",
    "chair leg",
    "price tag",
    "instruction",
    "catcher's mitt",
    "rooster",
    "soccer field",
    "museum",
    "blue hat",
    "baseline",
    "broccoli floret",
    "9",
    "clouds sky",
    "valance",
    "left shoe",
    "front door",
    "teacup",
    "basketball",
    "support beam",
    "crossing",
    "blue umbrella",
    "wording",
    "flip phone",
    "man's shirt",
    "insignia",
    "shin guards",
    "purple flowers",
    "satellite dish",
    "head board",
    "dinosaur",
    "red flowers",
    "frying pan",
    "tree limb",
    "white socks",
    "skate ramp",
    "iphone",
    "meatball",
    "bite",
    "curl",
    "windmill",
    "letter e",
    "second floor",
    "area rug",
    "wicker basket",
    "parking space",
    "raincoat",
    "tile wall",
    "black lettering",
    "windscreen",
    "drinking glass",
    "parade",
    "powdered sugar",
    "7",
    "long neck",
    "cute kitten",
    "young focused kid",
    "banana peel",
    "blood",
    "placard",
    "large tree",
    "c",
    "rear end",
    "curtain rod",
    "apartment building",
    "alley",
    "flower bed",
    "vane",
    "person standing",
    "cube",
    "rubber",
    "waterway",
    "creek",
    "brown table",
    "plaid",
    "coconut",
    "wig",
    "tier",
    "foot prints",
    "macaroni",
    "sideline",
    "exhibit",
    "young kid",
    "white top",
    "tide",
    "bookbag",
    "parked",
    "kitchen counter",
    "shovel",
    "water tank",
    "cleaner",
    "earphone",
    "mit",
    "flusher",
    "spring",
    "green jacket",
    "contrail",
    "black dog",
    "zebra head",
    "brake lights",
    "cross walk",
    "powerline",
    "grey shirt",
    "fist",
    "hardwood floor",
    "wine bottles",
    "front wheels",
    "doily",
    "mist",
    "chili",
    "caboose",
    "8",
    "turn signal",
    "raisin",
    "black cat",
    "tail feather",
    "washer",
    "cooker",
    "arched window",
    "brochure",
    "thermostat",
    "seal",
    "rafter",
    "lightbulb",
    "skeleton",
    "no object",
    "foundation",
    "flat",
    "white helmet",
    "blue wall",
    "dune",
    "tree trunks",
    "bundle",
    "yellow light",
    "razor",
    "nike",
    "number 4",
    "jumper",
    "snowman",
    "headlamp",
    "elephant leg",
    "imprint",
    "cpu",
    "hardware",
    "backrest",
    "number 5",
    "spread",
    "d",
    "blue light",
    "lawn chair",
    "frog",
    "batter's box",
    "boogie board",
    "giraffe head",
    "conveyor belt",
    "pitcher's mound",
    "cafe",
    "rung",
    "brown dirt",
    "foot print",
    "mold",
    "shack",
    "mom",
    "clear glass",
    "coin slot",
    "red coat",
    "company name",
    "savannah",
    "bandage",
    "baby giraffe",
    "gray pants",
    "right shoe",
    "hind legs",
    "medal",
    "blinder",
    "wildebeest",
    "baseball mitt",
    "computer tower",
    "sandy beach",
    "lounge chair",
    "old man",
    "station wagon",
    "white arrow",
    "moulding",
    "candlestick",
    "glass bottle",
    "transformer",
    "blue helmet",
    "open door",
    "white water",
    "stereo",
    "glass pane",
    "indentation",
    "beet",
    "stamp",
    "polish",
    "tab",
    "hanging",
    "black cap",
    "employee",
    "white light",
    "rv",
    "green bushes",
    "three people",
    "ladle",
    "slit",
    "jump",
    "bar stool",
    "woman's face",
    "parking sign",
    "pig",
    "black top",
    "red apple",
    "capri",
    "electronic",
    "person sitting",
    "pull",
    "wooden door",
    "signature",
    "apple logo",
    "grapefruit",
    "kite string",
    "finger nail",
    "graffitti",
    "flock",
    "black sign",
    "piping",
    "bay",
    "present",
    "fire place",
    "rabbit",
    "fold",
    "street corner",
    "wind",
    "home base",
    "baseball diamond",
    "behind",
    "reed",
    "snow boarder",
    "here",
    "mozzarella",
    "lorry",
    "back end",
    "lightpost",
    "knife block",
    "one way",
    "front light",
    "individual",
    "i",
    "filling",
    "red line",
    "electrical pole",
    "judge",
    "river bank",
    "red letters",
    "marquee",
    "letter r",
    "show",
    "wedge",
    "sweatpants",
    "black belt",
    "ferry",
    "wooden board",
    "wall tile",
    "front paw",
    "aeroplane",
    "white t-shirt",
    "throw",
    "melted cheese",
    "edging",
    "instrument",
    "sub",
    "loveseat",
    "airliner",
    "anchor",
    "silver fork",
    "model",
    "touchpad",
    "white pole",
    "title",
    "tree tops",
    "commode",
    "orange light",
    "lodge",
    "backdrop",
    "grassy",
    "seashell",
    "extinguisher",
    "brown dog",
    "rhino",
    "parka",
    "number 7",
    "tissue paper",
    "ceramic",
    "toaster oven",
    "clocktower",
    "dining room",
    "event",
    "parked car",
    "sandles",
    "alcohol",
    "black cord",
    "escalator",
    "linen",
    "polo",
    "yellow stripe",
    "red truck",
    "woman's hair",
    "power button",
    "store sign",
    "white hair",
    "brown shirt",
    "bra",
    "bus driver",
    "white face",
    "lap top",
    "train window",
    "panda bear",
    "ski stick",
    "homeplate",
    "fruit stand",
    "snowpants",
    "dry grass",
    "waffle",
    "green peppers",
    "washing machine",
    "oval",
    "arrangement",
    "thermos",
    "clipboard",
    "rocking chair",
    "plaza",
    "arena",
    "warehouse",
    "blonde",
    "blue top",
    "underwear",
    "nest",
    "l",
    "bug",
    "ski track",
    "tee",
    "bit",
    "yellow bananas",
    "desk lamp",
    "shore line",
    "ambulance",
    "white trim",
    "crow",
    "address",
    "rear window",
    "waste basket",
    "haircut",
    "headrest",
    "cell",
    "shelving",
    "terrace",
    "earth",
    "walk way",
    "polo shirt",
    "window panel",
    "tuxedo",
    "giraffe's head",
    "baseball helmet",
    "tanker",
    "winter",
    "space bar",
    "railway line",
    "headset",
    "city bus",
    "roller",
    "electronic device",
    "licence plate",
    "barcode",
    "black stripes",
    "double doors",
    "black numbers",
    "bunny",
    "macbook",
    "black tail",
    "arm band",
    "white dog",
    "poop",
    "g",
    "potatoe",
    "satellite",
    "document",
    "small tree",
    "sconce",
    "coke",
    "white bag",
    "concrete wall",
    "white table",
    "white frame",
    "towel holder",
    "exit",
    "year",
    "dent",
    "green field",
    "shine",
    "shampoo",
    "rubber band",
    "black strap",
    "semi truck",
    "chain link",
    "turban",
    "truss",
    "high chair",
    "bottle cap",
    "white frisbee",
    "wastebasket",
    "electric pole",
    "red roof",
    "index finger",
    "chrome",
    "advertisment",
    "front windshield",
    "dirt path",
    "bathroom floor",
    "video camera",
    "silver spoon",
    "black and white",
    "eyeball",
    "flower design",
    "red train",
    "foreleg",
    "white fur",
    "white number",
    "green bean",
    "white box",
    "number 9",
    "water body",
    "dump truck",
    "shoe lace",
    "electrical wires",
    "red helmet",
    "stake",
    "stuffed toy",
    "spindle",
    "tennis balls",
    "raquet",
    "baseball jersey",
    "pizza cutter",
    "jet plane",
    "blackberry",
    "shawl",
    "kitchen sink",
    "hall",
    "vending machine",
    "white foam",
    "grass area",
    "street pole",
    "grey pants",
    "red cap",
    "man's arm",
    "thumbnail",
    "son",
    "kneepads",
    "bathroom wall",
    "habitat",
    "barefoot",
    "missile",
    "happy little paint",
    "green vegetable",
    "laptop screen",
    "table leg",
    "lump",
    "wildebeast",
    "large building",
    "dark spot",
    "flower vase",
    "hammer",
    "glass vase",
    "cabinet doors",
    "green plants",
    "rump",
    "wearing",
    "chive",
    "sea foam",
    "gum",
    "message",
    "striped",
    "black gloves",
    "bandanna",
    "seat cover",
    "father",
    "speedometer",
    "dolphin",
    "surboard",
    "almond",
    "teen",
    "desk chair",
    "white jacket",
    "grid",
    "entry",
    "car door",
    "blue cap",
    "blue chair",
    "check",
    "silver pole",
    "badsentence",
    "growth",
    "tire tracks",
    "fireman",
    "left wrist",
    "grout line",
    "dead grass",
    "course",
    "10",
    "clamp",
    "double decker",
    "orange fruit",
    "wood post",
    "soap holder",
    "sol",
    "visible",
    "gleeful young woma",
    "wiring",
    "goblet",
    "paper cup",
    "red shorts",
    "tall",
    "flake",
    "mountain side",
    "tea cup",
    "booklet",
    "perch",
    "veil",
    "jungle",
    "flight",
    "surfboarder",
    "cheese pizza",
    "fence pole",
    "bright light",
    "wedding cake",
    "dove",
    "light house",
    "cutter",
    "livestock",
    "eating",
    "h",
    "bath",
    "coast",
    "cave",
    "cantaloupe",
    "blue letter",
    "hard hat",
    "brown pants",
    "kiosk",
    "red flag",
    "peacock",
    "tall trees",
    "ruler",
    "phone number",
    "rear view mirror",
    "bed sheet",
    "bonnet",
    "silo",
    "black seat",
    "white chair",
    "trackpad",
    "glass panel",
    "top hat",
    "front windows",
    "yogurt",
    "head lights",
    "tread",
    "engineer",
    "knee brace",
    "pigtail",
    "passenger windows",
    "bidet",
    "forefront",
    "pecan",
    "black eyes",
    "dinner plate",
    "buiding",
    "bright",
    "receptacle",
    "pit",
    "garland",
    "salsa",
    "diaper",
    "paper holder",
    "no leaves",
    "truck bed",
    "carnation",
    "sprout",
    "yellow tag",
    "jewelry",
    "pelican",
    "strand",
    "apple slice",
    "bulletin board",
    "system",
    "bikini top",
    "garbage bag",
    "squirrel",
    "motocycle",
    "gift",
    "bale",
    "white sink",
    "record",
    "love seat",
    "ruffle",
    "joint",
    "backyard",
    "hilltop",
    "water glass",
    "beach umbrella",
    "pine needles",
    "satchel",
    "blue paint",
    "server",
    "number 12",
    "duffle bag",
    "carousel",
    "viewer",
    "safety helmet",
    "letter n",
    "kale",
    "carrot slice",
    "calm water",
    "brown building",
    "rock formation",
    "stone building",
    "black frame",
    "wedding ring",
    "mini van",
    "buliding",
    "water tower",
    "windsheild",
    "four legs",
    "red chair",
    "cot",
    "mobile",
    "spaghetti",
    "black chair",
    "red lettering",
    "out",
    "plane tail",
    "grassland",
    "dolly",
    "tricycle",
    "motion",
    "chocolate cake",
    "left paw",
    "people sitting",
    "warning sign",
    "white wave",
    "white print",
    "ball player",
    "sticky note",
    "alarm",
    "pavers",
    "white napkin",
    "trophy",
    "carafe",
    "sushi",
    "crib",
    "green bottle",
    "spacebar",
    "hotel room",
    "man hole",
    "dark pants",
    "street lamps",
    "volleyball",
    "roof top",
    "forward",
    "oven mitt",
    "shot",
    "hitter",
    "her",
    "letter c",
    "hair tie",
    "game control",
    "fingertip",
    "riverbank",
    "tiled floor",
    "black hands",
    "yellow paint",
    "water drop",
    "basil leaf",
    "giraffe leg",
    "file",
    "indoors",
    "notice",
    "vendor",
    "duckling",
    "lattice",
    "hub cap",
    "wall paper",
    "large window",
    "young woman",
    "motorcyle",
    "gray sky",
    "washcloth",
    "crop",
    "dirt ground",
    "red onion",
    "white plane",
    "yellow jacket",
    "glass bowl",
    "mayo",
    "towel bar",
    "plum",
    "shirt sleeve",
    "snow skis",
    "salmon",
    "dinning table",
    "cilantro",
    "speckle",
    "small ripples",
    "webcam",
    "red bricks",
    "wrench",
    "pocketbook",
    "red building",
    "wet",
    "white clock",
    "person's",
    "sale",
    "expression",
    "fedora",
    "ticket",
    "big",
    "dog collar",
    "bike seat",
    "countryside",
    "hoove",
    "tofu",
    "baby carrot",
    "zebra tail",
    "white bird",
    "paddle board",
    "whiteboard",
    "blue coat",
    "lable",
    "building.",
    "blue plate",
    "register",
    "champagne",
    "bulding",
    "pavilion",
    "ray",
    "traffic signals",
    "wood frame",
    "white cloth",
    "wedding band",
    "white tag",
    "car seat",
    "box car",
    "village",
    "bed cover",
    "smoke detector",
    "red top",
    "support pole",
    "brow",
    "freeway",
    "shark",
    "tiled",
    "leather jacket",
    "freezer door",
    "big ben",
    "downhill",
    "coal",
    "dead tree",
    "crayon",
    "makeup",
    "black sock",
    "red tie",
    "bikers",
    "digit",
    "red paint",
    "attire",
    "clutter",
    "aquarium",
    "street name",
    "parking meters",
    "hair band",
    "buidling",
    "electrical line",
    "story",
    "brown tree",
    "sink faucet",
    "wood grain",
    "rink",
    "smudge",
    "red lights",
    "dimple",
    "horse's head",
    "fighter jet",
    "floral pattern",
    "ditch",
    "motorcycle helmet",
    "onion ring",
    "tram",
    "route",
    "metal rail",
    "stubble",
    "light glare",
    "green pole",
    "peanut butter",
    "food piece",
    "white paint",
    "tooth brush",
    "refrigerator door",
    "hotdog bun",
    "number 8",
    "skateboard wheel",
    "elephant tusk",
    "peace sign",
    "blue line",
    "six",
    "pacifier",
    "scallion",
    "bare feet",
    "number 6",
    "wet sand",
    "crouton",
    "parent",
    "tick",
    "backboard",
    "red circle",
    "body of water",
    "long sleeve",
    "person walking",
    "rear light",
    "khaki pants",
    "parking area",
    "brown leaves",
    "wineglass",
    "peg",
    "glass jar",
    "brown jacket",
    "pot holder",
    "paved road",
    "bouy",
    "peanut",
    "seabird",
    "bare trees",
    "barge",
    "blemish",
    "roofing",
    "loaf",
    "rudder",
    "loafer",
    "skiiers",
    "two giraffes",
    "train door",
    "onlooker",
    "fastener",
    "toe nail",
    "man standing",
    "mid air",
    "hand soap",
    "toliet",
    "sport",
    "spear",
    "honey",
    "white frosting",
    "old tree",
    "white button",
    "cheese cube",
    "eraser",
    "electrical box",
    "spray bottle",
    "spare tire",
    "router",
    "sprinkler",
    "top shelf",
    "phone booth",
    "icicle",
    "ride",
    "brown chair",
    "way",
    "black fence",
    "sign board",
    "bare tree",
    "pinky",
    "strainer",
    "sideview mirror",
    "white bus",
    "letter b",
    "man's wrist",
    "solar panel",
    "walker",
    "dish towel",
    "baggage",
    "sun visor",
    "sidecar",
    "nipple",
    "k",
    "company",
    "skateboard park",
    "patty",
    "giraffe's",
    "sponsor",
    "salami",
    "black tie",
    "cubicle",
    "classroom",
    "yellow wall",
    "kitchen cabinet",
    "head rest",
    "cherry tomato",
    "shopper",
    "brown bag",
    "construction",
    "flash",
    "daylight",
    "bald head",
    "shelve",
    "black wheels",
    "hatchback",
    "pet",
    "red trim",
    "wrapping",
    "sweat shirt",
    "turret",
    "giraffe neck",
    "rowboat",
    "black suitcase",
    "baby zebra",
    "mobile phone",
    "duffel bag",
    "man's foot",
    "side windows",
    "horse head",
    "wiimote",
    "man sitting",
    "flying",
    "duvet",
    "walnut",
    "potato chip",
)
num_classes = len(class_name)
metainfo = dict(classes=class_name, palette=[(20, 220, 60)])

close_mosaic_epochs = 10

max_epochs = 100
train_batch_size_per_gpu = 32
train_num_workers = 8

load_from = "https://download.openmmlab.com/mmyolo/v0/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco/yolov8_s_syncbn_fast_8xb16-500e_coco_20230117_180101-5aa5f0f1.pth"  # noqa

model = dict(
    backbone=dict(frozen_stages=4),
    bbox_head=dict(head_module=dict(num_classes=num_classes)),
    train_cfg=dict(assigner=dict(num_classes=num_classes)),
)

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="annotations/train.json",
        data_prefix=dict(img="images/"),
    ),
)

val_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file="annotations/val.json",
        data_prefix=dict(img="images/"),
    )
)

test_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file="annotations/test.json",
        data_prefix=dict(img="images/"),
    )
)

_base_.optim_wrapper.optimizer.batch_size_per_gpu = train_batch_size_per_gpu
_base_.custom_hooks[1].switch_epoch = max_epochs - close_mosaic_epochs

val_evaluator = dict(
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file= data_root + 'annotations/val.json',
    metric='bbox')
test_evaluator = dict(
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file=data_root + 'annotations/test.json',
    metric='bbox')

default_hooks = dict(
    checkpoint=dict(interval=10, max_keep_ckpts=2, save_best="auto"),
    # The warmup_mim_iter parameter is critical.
    # The default value is 1000 which is not suitable for cat datasets.
    param_scheduler=dict(max_epochs=max_epochs, warmup_mim_iter=10),
    logger=dict(type="LoggerHook", interval=1000),
)
train_cfg = dict(max_epochs=max_epochs, val_interval=10)
# visualizer = dict(vis_backends = [dict(type='LocalVisBackend'), dict(type='WandbVisBackend')]) # noqa
